#!/usr/bin/env bash

# Name:     certbot-renew
# Author:   David Vogel <david@davidvogel.xyz>
# Date:     2026 Jan 3, Sat
# License:  GPL v3.0
# Desc:     `certbot-renew` renews Let's Encrypt certificates.

CERT_DIR="/etc/letsencrypt/live/*/fullchain.pem"
UFW_RULES_FILE="/etc/ufw/user.rules"

# If certs expire in less than `RENEW_TIME`, renew the certs
RENEW_TIME=28

# Assume open access to HTTP is disabled (checked during `open_firewall`)
HTTP_ACCESS=false

# Prints provided message to STDERR; then, exits with return code `1`
error() {
    echo "$1" >&2 \
        && exit 1
}

log_stamp() {
    date +"%Y %b %e %T:"
}

root_check() {
    if ! [[ "$(whoami)" == "root" ]]; then
        error "$(log_stamp) [ERROR]: This script must be run with root privileges. Exiting now."
    fi
}

dep_check() {
    if ! [[ $(command -v certbot) ]]; then
        error "$(log_stamp) [ERROR]: \`certbot\` does not appear to be installed. Exiting now."
    fi
}

# Checks for open access to port 80 (HTTP)
# If port is open, do nothing
# If port is not open, open it; then, ready it for close when script exits
open_firewall() {
    if ! [[ $(command -v ufw) ]]; then
        return 0
    else
        # Check for open access to "port 80 TCP" (HTTP)
        while read -r line; do
            if [[ "$line" =~ "allow tcp 80 0.0.0.0/0 any 0.0.0.0/0" ]]; then
                HTTP_ACCESS=true
                break
            fi
        done < "$UFW_RULES_FILE"

        # If "port 80 TCP (HTTP)" is closed, temporarily open it
        if [[ "$HTTP_ACCESS" == false ]]; then
            ufw allow to any port 80 proto tcp > /dev/null 2>&1
            echo "$(log_stamp) [INFO]: UFW rule \"open port 80 TCP (HTTP)\" was temporarily added."
        fi
    fi
}

cleanup() {
    if ! [[ $(command -v ufw) ]]; then
        return 0
    else
        if [[ "$HTTP_ACCESS" == false ]]; then
            ufw delete allow to any port 80 proto tcp > /dev/null 2>&1
            echo "$(log_stamp) [INFO]: UFW rule \"open port 80 TCP (HTTP)\" was deleted."
        fi
    fi

    echo "$(log_stamp) [INFO]: Cleanup operations completed successfully!"
}

renew_certs() {
    certbot renew -q
    echo -e "$(log_stamp) [INFO]: Certificates renewed successfully!\n"
    exit 0
}

check_cert() {
    while read -r line; do
        local DATE_CERT="${line//notAfter=}"
        read -r m d t y tz <<< "$DATE_CERT"
        DATE_CERT="$(($(date -d "$m $d $y" +%s) / 86400))"
    done < <(openssl x509 -in "$1" -noout -enddate)

    if ! [[ "$DATE_CERT" ]]; then
        echo "$(log_stamp) [WARN]: Could not read the expiration date for \`$1\`."
        return 1
    fi

    local TIME_REMAINING="$((DATE_CERT - DATE_TODAY))"

    if ((TIME_REMAINING > RENEW_TIME )); then
        echo "$(log_stamp) [INFO]: \`$1\` expires in $TIME_REMAINING days, which is greater than $RENEW_TIME days."
    else
        echo -e "\n$(log_stamp) [INFO]: \`$1\` expires in $TIME_REMAINING days, which is fewer than $RENEW_TIME days."
        echo -e "$(log_stamp) [INFO]: Attempting to renew certs..."

        open_firewall
        trap cleanup exit
        echo -e "$(log_stamp) [INFO]: Script will delete temporary UFW rules after renewal."

        renew_certs
    fi
}

main() {
    root_check
    dep_check

    local DATE_TODAY="$(($(date +%s) / 86400))"
    local CERT_FILES=($CERT_DIR)
    local NUM_CERTS="${#CERT_FILES[@]}"

    # Check the Let's Encrypt SSL certificates
    for ((i=0; i < $NUM_CERTS; i++)); do
        check_cert "${CERT_FILES[i]}"
    done

    # If scripts calls the functions below, there were no certs to renew
    echo "$(log_stamp) [INFO]: No certificates were ready to be renewed."
    exit 0
}

main
